### ISSUE TITLE
Question - map headers

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#11]
Hi Mathielen,

Is it possible to map the headers per format to common header, which will allow 1 service be able to handle multiple importers

Example 1:  importer headers:
"header 1", "header 2"

==> mapped to "firstName", "lastName"

Example 2:  importer headers:
"Marco 1", "Polo 2"

==> mapped to "firstName", "lastName"

Which would help the service processImportRow method to recognize the variables easier and do something with them.

Regards,
Tim

**Comment by mathielen** [comment]
Hi Tim,

Sure:

```
importer1:
    mappings:
        "HEADER 1": "firstName"
        "HEADER 2": "lastName"
    target: [myService, processRow]

importer2:
    mappings:
        "MARCO 1": "firstName"
        "POLO 2": "lastName"
    target: [myService, processRow]
```

Best regards,
Markus

**Comment by thim81** [comment]
clear, thanks
