### ISSUE TITLE
Documentation request - context

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#14]
Hi Mathielen,

What is the purpose and use for the "context" property?

```
#some context information that is passed through the whole process
            context:
                key: bol
```

Regards,
Tim

**Comment by mathielen** [comment]
You can pass context information via the CLI-Command (-c) and/or at the importer configuration level (that you have mentioned). The context is just data that is associated with the import you are running. Use it to supply additional information while running an import. You get the context data via events.

For example, if you are using a service endpoint for the import, you can intercept the prepare event of the import and get the context information.

Register as listener for importer "myimport"
```xml
<service id="myimport.endpoint" class="Import\Endpoint\SomeService">
    <tag name="kernel.event_listener" event="data-import.prepare.myimport" method="prepare"/>
</service>
```

And in SomeService:
```php
public function prepare(Mathielen\DataImport\Event\ImportProcessEvent $event)
{
    $context = $event->getContext();
}
```

Best regards

**Comment by thim81** [comment]
Good to know, since it might come in handy to target specific cases for a generic service method
