### ISSUE TITLE
Documentation request - preconditions

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#15]
Another documentation request

```
            #automaticly recognize this importer by meeting of the conditions below
            preconditions:
                format: excel               #format of data must be [csv, excel, xml]
                fieldcount: 2               #must have this number of fields
                fields:                     #these fields must exist (order is irrelevant)
                    - 'header2'
                    - 'header1'
                fieldset:                   #all fields must exist exactly this order
                    - 'header1'
                    - 'header2'
#                filename: 'somefile.xls'    #filename must match one of these regular expression(s) (can be a list)
```

Questions:

- What is the difference between fields and fieldset? 
- What other properties can be set in the preconditions?
- Can the format be an array of formats like in your comment?
- Does your importer automatically detect if it's an CSV or excel?

Regards,
Tim

**Comment by mathielen** [comment]
Hey Tim,

-  Please have a look at the comments in the snippet :) 
  - "fields": these fields must exist (order is irrelevant)
  - "fieldset": all fields must exist exactly this order
- None. Do you have something in mind?
- Unfortunately, no. But it's a good idea. Will implement it.
- Yes (Also any other format that is registered). See https://github.com/mathielen/import-engine/blob/master/src/Mathielen/ImportEngine/Storage/Format/Discovery/MimeTypeDiscoverStrategy.php#L45

Best regards

**Comment by thim81** [comment]
- So fields and fieldset are the same except that the order is relevant for fieldset
- No extra preconditions to think off with the current use-cases i'm facing right now
- I would be a nice enhancement since it allows multiple formats to be processed by the same importer
- Impressive: I saw JSON and even zipped files ...

**Comment by mathielen** [comment]
- Thats right
- Just tell me, if you have any
- True
- :)
