### ISSUE TITLE
Class 'Infrastructure\Utils' not found 

### ISSUE THREAD

**Issue by nurikabe** [mathielen/ImportEngineBundle#2]
We're experimentally playing around with dev-master of the import engine.  ImportCommand is looking for Infrastructure/Utils which doesn't exist?  Missing commit perhaps?

**Comment by mathielen** [comment]
Sorry, there was an additional dependency for one simple call. I removed it. Please update the bundle. If you have any questions or feedback, I would be happy to hear it.
