### ISSUE TITLE
Documentation update - PHPExcel library

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#20]
If people want to sue the excel files, they should install the PHPExcel library, so perhaps you should add it to your documentation

> ExcelReader
> 
> Acts as an adapter for the PHPExcel library. Make sure to include that library in your project:
> 
> `$ composer require phpoffice/phpexcel`

Since in case you using it the followind error might appear.

`PHP Fatal error:  Interface 'PHPExcel_Reader_IReadFilter' not found in`

**Comment by mathielen** [comment]
Hi Tim,
Thats right.

Thanks as always
Markus
