### ISSUE TITLE
utf-8 in headers

### ISSUE THREAD

**Issue by Notmarrco** [mathielen/ImportEngineBundle#22]
I have a header list like this : 
```yml
fields:
    - 'Nom générique'
    - Nom
```

and when I import it I get a messed up field. I also can't map it to another target-field name because it isn't recognised.

Is there something I can do about it ?

thx

**Comment by thim81** [comment]
Hi Notmarrco,

Can you try with '' arround all fields?
Or try with ""?

Another tip: the fields definition is to check if these fields exist, not to map.
This happens in the "mappings" part.

Here is an example of a part my config:

```
 #automaticly recognize this importer by meeting of the conditions below
            preconditions:
                format: excel               #format of data must be csv OR excel OR xml
                fieldcount: 2               #must have this number of fields
                fields:                     #these fields must exist (order is irrelevant)
                    - 'Receiver phone'
                    - 'Street'
                    - 'House number'
                    - 'Zipcode'
                    - 'City'

            #add mapping
            mappings:
                # Rename headers to appropriate variables
                "Receiver firstname": "delivery-receiver-firstName"
                "Receiver name": "delivery-receiver-lastName"
```

**Comment by Notmarrco** [comment]
Hi !

Yes I did try with '' and "" but it doesn't change a thing.

In fact all the content of the file is also messed up because of the utf-8 format. It doesn't import the values after the first utf-8 character it encounters.

So the bundle has to handle variations in encoding for the all file. I don't know if it's possible in ddboer package so that we could use it.

As for the mapping, it's my fault, I haven't been explicit enough : 

I did try the ```mappings``` section, but it doesn't work because it can't map my header with the conf since the header in the mapping is something like "héllo" but the importer gives me "h$#llo" instead :smile:

**Comment by thim81** [comment]
This is something I guess is handled by the import bundle, which I think is currently not supported.

But only Markus can confirm for sure.

**Comment by mathielen** [comment]
Hi guys,

Sorry for all the delay. Been very busy these days.
So regarding variations in encoding: that wont work at all. The file should have one specific encoding and stick by it. Maybe there are some other (mostly bash-based) tools that might fix the file and set the content to a defined encoding. Something like iconv or recode...?

Please try to UPPERCASE the mappings-keys (the field names). That should do the trick. And of course the file should have a correct encoding. Try UTF8.

Best regards
Markus
