### ISSUE TITLE
DateTimeThresholdFilter expects parameter

### ISSUE THREAD

**Issue by Avtonom** [mathielen/ImportEngineBundle#7]
if use
````php
                $event->getImport()->importer()->filters()->add(new DateTimeThresholdFilter(
                    new DateTimeValueConverter(),
                    new \DateTime($dateFilterDate),
                    $dateFilterColumn
                ));
````

and ORM Entity type="datetime"

````php
    /**
     * @var \DateTime
     * @ORM\Column(name="date_created", type="datetime", nullable=true)
     */
    protected $dateCreated;
````

view error:
 ``
[Exception]
  DateTime::__construct() expects parameter 1 to be string, object given
 ``

 ``
Exception trace:
 () at vendor/ddeboer/data-import/src/Ddeboer/DataImport/ValueConverter/DateTimeValueConverter.php:64
 DateTime->__construct() at vendor/ddeboer/data-import/src/Ddeboer/DataImport/ValueConverter/DateTimeValueConverter.php:64
 Ddeboer\DataImport\ValueConverter\DateTimeValueConverter->convert() at vendor/ddeboer/data-import/src/Ddeboer/DataImport/Filter/DateTimeThresholdFilter.php:57
 Ddeboer\DataImport\Filter\DateTimeThresholdFilter->filter() at vendor/ddeboer/data-import/src/Ddeboer/DataImport/Workflow.php:297
 Ddeboer\DataImport\Workflow->filterItem() at vendor/mathielen/import-engine/src/Mathielen/DataImport/EventDispatchableWorkflow.php:111
 Mathielen\DataImport\EventDispatchableWorkflow->processFilter() at vendor/mathielen/import-engine/src/Mathielen/DataImport/EventDispatchableWorkflow.php:48
 Mathielen\DataImport\EventDispatchableWorkflow->process() at vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Import/Run/ImportRunner.php:56
 Mathielen\ImportEngine\Import\Run\ImportRunner->process() at vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Import/Run/ImportRunner.php:107
``

Problem in vendor/ddeboer/data-import/src/Ddeboer/DataImport/ValueConverter/DateTimeValueConverter.php:64

````php
$date = new \DateTime($input);
````

If use type="string" to OK

**Comment by Avtonom** [comment]
if use
````php
                $event->getImport()->importer()->filters()->add(new DateTimeThresholdFilter(
                    new GenericDateItemConverter(), !!!!!!
                    new \DateTime($dateFilterDate),
                    $dateFilterColumn
                ));
````

 Warning: Missing argument 1 for Mathielen\DataImport\ValueConverter\GenericDateItemConverter::__construct(), called in vendor/mathielen/import-engine-bundle/Mathielen/ImportEngineBundle/Command/ImportCommand.php on line 101 and defined

**Comment by Avtonom** [comment]
@mathielen https://github.com/Avtonom/ImportEngineBundle/commit/9db65de9c6e1f06a2404e24d26fd49988458c9c6

**Comment by mathielen** [comment]
Please use your own Converter then. GenericDateItemConverter expects a string.
