### ISSUE TITLE
Issue -  a dependency on a non-existent service

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#9]
When using a service as a target, in the app/config/config.yml

I get the following error:
```
 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                              
  The service "mathielen_importengine.importer.repository" has a dependency on a non-existent service "@parcel_service". 
```

I seems that my service is not yet loaded.

**Comment by mathielen** [comment]
You should omit the @. If that doesnt work, please show me your config.

**Comment by thim81** [comment]
Thanks we figured it out just now, before we saw your comment.

Could you explain why the @ is not needed anymore? 

And perhaps it's useful to update the doc or add it this as without @ as alternate config?

Either way, I just love how a simple config.yml is able to process a whole excel file and return cleaned-up data and that you can configure multiple importers all from config.yml

**Comment by mathielen** [comment]
Sure. As you already have configured the output as being a service, you dont have to define it as a reference to a service (using @) anymore. But I think it might be a good thing to also allow @, just for the convenience.

Great. If you have any other ideas or problems, just open an issue.
